// Generated by scripts/generate-images.mjs. Do not edit by hand.
// Imagery generated with google/gemini-2.5-flash-image via OpenRouter, then
// encoded to WebP for delivery. The PNG masters live in `source-assets/`.

export type SiteImage = {
  src: string;
  width: number;
  height: number;
  alt: string;
  generated: boolean;
};

export const images = {
  approach: {
    src: "/images/approach.webp",
    width: 1184,
    height: 864,
    alt: "A layered system architecture rendered as glowing tiers above a circuit board",
    generated: true,
  },
  capabilityAi: {
    src: "/images/capabilityAi.webp",
    width: 1536,
    height: 1024,
    alt: "A glowing neural network brain rising from a processor on a circuit board",
    generated: false,
  },
  capabilityAutomation: {
    src: "/images/capabilityAutomation.webp",
    width: 1536,
    height: 1024,
    alt: "A central gear linked by glowing paths to icons for data, mail, reporting and cloud services",
    generated: false,
  },
  serviceWeb: {
    src: "/images/serviceWeb.webp",
    width: 1248,
    height: 832,
    alt: "A glowing browser window floating above a circuit board",
    generated: true,
  },
  serviceApps: {
    src: "/images/serviceApps.webp",
    width: 1248,
    height: 832,
    alt: "Interlocking application panels connected above a circuit board",
    generated: true,
  },
  serviceDesign: {
    src: "/images/serviceDesign.webp",
    width: 1248,
    height: 832,
    alt: "Design layers rising from wireframe to finished interface",
    generated: true,
  },
  contact: {
    src: "/images/contact.webp",
    width: 1248,
    height: 832,
    alt: "A glowing globe of connected nodes above a circuit board",
    generated: true,
  },
} satisfies Record<string, SiteImage>;

export type ImageId = keyof typeof images;
